name: Deploy para as páginas do GitHub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o repositório
        uses: actions/checkout@v3
  
      - name: Configurar o GitHub Pages
        uses: actions/configure-pages@v3
  
      - name: Criar arquivos para o deploy
        uses: actions/upload-pages-artifact@v2
        with:
          path: .
  
      - name: Publicar no GitHub Pages
        uses: actions/deploy-pages@v1
