name: Deploy para o GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checa o repositório
      - name: Checa o repositório
        uses: actions/checkout@v3

      # Passo 2: Gera os arquivos para o deploy (exemplo para uma aplicação React)
      - name: Instala dependências e cria o build
        run: |
          npm install
          npm run build  
          
        # Substitua por comandos específicos para sua aplicação

      # Passo 3: Faz o deploy dos artefatos para o GitHub Pages
      - name: Deploy no GitHub Pages
        uses: actions/deploy-pages@v2
