name: Deploy para as páginas do GitHub

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

  steps:
    - name: Checa o repositorio
      uses: actions/checkout@v3

    - name: Configura o GitHub Pages
      uses: actions/configure-pages@v3

    - name: Cria arquivos para deploy
      uses: actions/upload-pages-artifact@v3
      with:
        path:

    - name: Publica no GitPages
      uses: actions/deploy-pages@v1
