name: Deploy para as páginas do GitHub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checa o repositório
        uses: actions/checkout@v3

      - name: Configura o GitHub Pages
        uses: actions/configure-pages@v2

      - name: Cria arquivos para Deploy
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build  # Ou o caminho correto onde seus arquivos de build estão

      - name: Publica no GitHub Pages
        uses: actions/deploy-pages@v2
